# Generated by Django 4.1.3 on 2022-12-13 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('1s', '*'), ('2s', '**'), ('3s', '***'), ('4s', '****'), ('5s', '*****')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
