# Generated by Django 4.1.3 on 2022-12-13 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='detail',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(blank=True, choices=[('1s', '*'), ('2s', '**'), ('3s', '***'), ('4s', '****'), ('5s', '*****')], max_length=2),
        ),
    ]
