# Generated by Django 4.1.3 on 2022-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(blank=True, choices=[('⭐', '1 star'), ('⭐⭐', '2 star'), ('⭐⭐⭐', '3 star'), ('⭐⭐⭐⭐', '4 star'), ('⭐⭐⭐⭐⭐', '5 star')], max_length=5),
        ),
    ]
