# Generated by Django 4.1.3 on 2022-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField()),
                ('interestes', models.CharField(max_length=200)),
            ],
        ),
    ]
