# Generated by Django 4.1.3 on 2022-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutadmin',
            name='age',
        ),
        migrations.AlterField(
            model_name='aboutadmin',
            name='degree',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutadmin',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutadmin',
            name='interestes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutadmin',
            name='website',
            field=models.CharField(max_length=40),
        ),
    ]
