# Generated by Django 4.1.3 on 2022-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_aboutadmin_age_alter_aboutadmin_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutadmin',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
