# Generated by Django 4.1.3 on 2022-12-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutadmin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutadmin',
            name='age',
            field=models.IntegerField(default=26),
        ),
    ]
