# Generated by Django 4.1.3 on 2022-12-05 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adminservice_alter_aboutadmin_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminservice',
            old_name='service',
            new_name='serviceNameMajor',
        ),
        migrations.AddField(
            model_name='adminservice',
            name='serviceNameMinor',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
